import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Content from '../components/content'
import Footer from '../components/footer'
import Navbar from '../components/navbar'




const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Loophole</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Content />

      <Footer />
    </div>
  )
}

export default Home
